Blog section
appweave-tech/website pull request #12
Opened 2024-07-05 06:54 UTC by shivah12

![Screenshot_5-7-2024_122216_localhost](https://github.com/appweave-tech/website/assets/114981873/d5c82a40-c7eb-47e1-bfe1-b65fe81ecaf6)
![Screenshot_4-7-2024_13614_localhost](https://github.com/appweave-tech/website/assets/114981873/5297af31-182e-47e5-a9de-2eee89e6b905)

Added blog section in home page working on improving the blog details page and adding page for viewing all blogs.

2024-07-05 10:01 UTC, Arioum requested changes

2024-07-05 10:01 UTC, Arioum commented on static/admin/config.yml
> -      - { label: "Description", name: "description", widget: "text" }
Undo this change as this effects the project-page section.

2024-07-05 10:01 UTC, Arioum commented on static/admin/config.yml
> +              label: "Services",
Undo any changes here, for this file that is - 
1. Not related to your PR (Blog)
2. Quote related changes.

2024-07-05 10:01 UTC, Arioum commented on static/admin/config.yml
>        - { label: "Description", name: "description", widget: "string" }
change the widget value for the description field from `string` to `text` (refer project page for this)

2024-07-05 10:01 UTC, Arioum commented on src/pages/index.tsx
> -          fields {
Undo this change

2024-07-05 10:01 UTC, Arioum commented on src/pages/index.tsx
> +      <Navbar />
Undo this change, just uncomment the `FeaturedBlog` is enough

2024-07-05 10:01 UTC, Arioum commented on gatsby-node.ts
> -  if (!result.data) {
You can keep this, no need to remove

2024-07-09 15:30 UTC, Arioum approved these changes

2024-07-22 18:20 UTC, saurabh73 approved these changes

2024-07-22 18:20 UTC, merged