Updatedcontact
appweave-tech/website pull request #5
Opened 2024-06-20 12:44 UTC by fThAbhishek-Pandey

![image](https://github.com/appweave-tech/website/assets/121682915/771786c2-48bd-4aee-8a4f-eb2bcafd8e3b)
improving image path

2024-06-20 13:50 UTC, Arioum commented
LGTM👍🏻

2024-06-20 13:57 UTC, Arioum commented on src/components/Contact.tsx
> +                      <Box py={{ base: 5, sm: 5, md: 8, lg: 10 }}w={"100%"} >
There appears to be no space between `py `and `w `attribute. Is the `w` still working as expected?

2024-06-21 14:54 UTC, ptabhishekutopia commented
> Try not to use `<center/>` tag. It works, but it is deprecated and not encouraged.

I will trying to  fixed this email

2024-06-24 17:00 UTC, Arioum commented
2 minor things you can improve:

**1. Centering of the below elements when the screen size is less:**
[<img src="https://github.com/appweave-tech/website/assets/95125149/938de84a-15d1-4c20-b793-ba981b3fba9f" width="450"/>](image.png)



**2. Try giving space between the contact form and the footer:**
[<img src="https://github.com/appweave-tech/website/assets/95125149/e03e6c08-4344-4f5a-8b6b-2ea339f7c15d" width="450"/>](image.png)

2024-06-24 17:15 UTC, fThAbhishek-Pandey commented
> 2 minor things you can improve:
> 
> **1. Centering of the below elements when the screen size is less:** [<img alt="" width="450" src="https://private-user-images.githubusercontent.com/95125149/342426526-938de84a-15d1-4c20-b793-ba981b3fba9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDkwMzQsIm5iZiI6MTcxOTI0ODczNCwicGF0aCI6Ii85NTEyNTE0OS8zNDI0MjY1MjYtOTM4ZGU4NGEtMTVkMS00YzIwLWI3OTMtYmE5ODFiM2ZiYTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE3MDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4OWFjZDMyMTdjMDJiYzliM2RkYTM0NzlhMGY0Njk2NTI5Y2JhZjI0MzlhMDdjN2YyNThhZmQ5ZmY5N2I4NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rj4Jnc17WYfaMoKn24N1dqK1IPAtalceCcuB1Fi3tao">](image.png)
> 
> **2. Try giving space between the contact form and the footer:** [<img alt="" width="450" src="https://private-user-images.githubusercontent.com/95125149/342428288-e03e6c08-4344-4f5a-8b6b-2ea339f7c15d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDkwMzQsIm5iZiI6MTcxOTI0ODczNCwicGF0aCI6Ii85NTEyNTE0OS8zNDI0MjgyODgtZTAzZTZjMDgtNDM0NC00ZjVhLThiNmItMmVhMzM5ZjdjMTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDE3MDUzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMTIwZmRhZTdhMmY2ZjdlNjcyYWUwYmE4OTZjZTIwZWJiMjcyNjI2NDkxMDcyZWNjZmFmODViNGJmZTMzNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4TP95zNobhKwyxvhAo2mwB4rdeTR_15rd-GunDmFxGM">](image.png)

I think content of address is more than other filled . so, the icon is shown large comparatibily

2024-07-03 05:40 UTC, saurabh73 requested changes

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Contact.tsx
> +                <center>
@fThAbhishek-Pandey Remove this

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Contact.tsx
> +      maxW={"100%"}
use `'6xl'`

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Contact.tsx
> +              w={"40%"}
give responsive width

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Contact.tsx
> +              p="6"
responsive padding values.

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Contact.tsx
> +            <Box w={"50%"}>
Use responsive width

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Footer.tsx
> +                <FaYoutube size={"3rem"} color="red.400" />
Should be Linkedin inon

2024-07-03 05:40 UTC, saurabh73 commented on src/components/Footer.tsx
> +                <FaTwitter size={"3rem"} />
Should query from Decap

2024-07-03 05:40 UTC, saurabh73 commented on src/data/index.md
> +        icon: FiInstagram
LinkedIn, Twitter and Email Icon

2024-07-03 05:40 UTC, saurabh73 commented on static/admin/config.yml
> +              label: 'Template Key',
Unnecessary change.

2024-07-03 05:40 UTC, saurabh73 commented on static/admin/config.yml
> +                              {
Unnecessary change.

2024-07-08 13:48 UTC, fThAbhishek-Pandey commented
resolved

2024-07-19 13:06 UTC, Arioum reviewed
### Can you fix this? 
Currently the form goes outside the viewport before being wrapped.
<br/>
**You can do this by:**
* Reducing the width of both image and form once they have no space. You can reset this width once it has wrapped. So keep the width responsive rather than fixed `px` value;

https://github.com/user-attachments/assets/6d1b9e62-7ad6-4217-b9f3-b8eba5c33c3d

2024-07-19 14:15 UTC, fThAbhishek-Pandey commented
> ### Can you fix this?
> Currently the form goes outside the viewport before being wrapped. **You can do this by:**
> 
> * Reducing the width of both image and form once they have no space. You can reset this width once it has wrapped. So keep the width responsive rather than fixed `px` value;
> 
>  mq-issue-outofbounds.mp4


Uploading Recording 2024-07-19 194428.mp4…

updated

2024-10-16 08:43 UTC, saurabh73 approved these changes

2024-10-16 08:43 UTC, merged